secretjob:
  enabled: true
  additionalAnnotations: { }
  additionalLabels: { }
  image:
    ##
    ##
    registry: docker.io
    ##
    ##
    repository: wazuh/wazuh-certs-generator
    ##
    ##
    tag: 0.0.2
    ##
    ##
    digest: ""
    ## Specify a imagePullPolicy
    ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
    ## ref: https://kubernetes.io/docs/concepts/containers/images/#pre-pulled-images
    ##
    pullPolicy: IfNotPresent
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ## e.g:
    ## pullSecrets:
    ##   - myRegistryKeySecretName
    ##
    pullSecrets: [ ]
  serviceAccount:
    name: wazuh-certs
  config:
    nodes:
      # Wazuh indexer server nodes
      indexer:
        - name: wazuh1.indexer
          ip: wazuh1.indexer
        - name: wazuh2.indexer
          ip: wazuh2.indexer
        - name: wazuh3.indexer
          ip: wazuh3.indexer

      # Wazuh server nodes
      # Use node_type only with more than one Wazuh manager
      server:
        - name: wazuh.master
          ip: wazuh.master
          node_type: master
        - name: wazuh.worker
          ip: wazuh.worker
          node_type: worker

      # Wazuh dashboard node
      dashboard:
        - name: wazuh.dashboard
          ip: wazuh.dashboard