global:
  ##
  ##
  domain: wazuh.example.com
  ##
  ##
  version: "4.8.2"
  ##
  ##
  imageRegistry: ""
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: [ ]
  ##
  ##
  storageClassName: ""

## @param kubeVersion Override Kubernetes version
##
kubeVersion: ""
## @param nameOverride String to partially override common.names.fullname template (will maintain the release name)
##
nameOverride: ""
## @param fullnameOverride String to fully override common.names.fullname template
##
fullnameOverride: ""
## @param commonLabels Labels to add to all deployed resources
##
commonLabels: { }
## @param commonAnnotations Annotations to add to all deployed resources
##
commonAnnotations:
  "kubernetes.io/description": "wazuh component"
## @param commonIngressAnnotations Annotations to add to all Ingress resources
##
commonIngressAnnotations: { }

##
##
storageClass:
  ##
  ##
  enabled: true
  ##
  ##
  name: ""
  ##
  ##
  additionalAnnotations: { }
  ##
  ##
  additionalLabels: { }
  ##
  ##
  provisioner: ""
  ##
  ##
  parameters: { }
  ##
  ##
  volumeBindingMode: ""
  ##
  ##
  reclaimPolicy: Delete

##
##
apiCred:
  ##
  ##
  auth:
    ##
    ##
    username: wazuh-wui
    ##
    ##
    password: "9Y0m^%^Cx4zx@6=X"

secretjob:
  enabled: true
  additionalAnnotations:
    "helm.sh/hook": pre-install
  additionalLabels: { }
  image:
    ##
    ##
    registry: docker.io
    ##
    ##
    repository: alpine
    ##
    ##
    tag: latest
    ##
    ##
    digest: ""
    ## Specify a imagePullPolicy
    ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
    ## ref: https://kubernetes.io/docs/concepts/containers/images/#pre-pulled-images
    ##
    pullPolicy: IfNotPresent
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ## e.g:
    ## pullSecrets:
    ##   - myRegistryKeySecretName
    ##
    pullSecrets: [ ]
  ##
  ##
  secretImage:
    ##
    ##
    registry: docker.io
    ##
    ##
    repository: bitnami/kubectl
    ##
    ##
    tag: latest
    ##
    ##
    digest: ""
    ## Specify a imagePullPolicy
    ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
    ## ref: https://kubernetes.io/docs/concepts/containers/images/#pre-pulled-images
    ##
    pullPolicy: IfNotPresent
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ## e.g:
    ## pullSecrets:
    ##   - myRegistryKeySecretName
    ##
    pullSecrets: [ ]
  ##
  ##
  serviceAccount:
    ##
    ##
    name: wazuh-certs

indexer:
  ##
  ##
  replicas: 2
  ##
  ##
  nameOverride: ""
  ##
  ##
  image:
    ##
    ##
    registry: docker.io
    ##
    ##
    repository: wazuh/wazuh-indexer
    ##
    ##
    tag: '{{ .Values.global.version }}'
    ##
    ##
    digest: ""
    ## Specify a imagePullPolicy
    ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
    ## ref: https://kubernetes.io/docs/concepts/containers/images/#pre-pulled-images
    ##
    pullPolicy: IfNotPresent
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ## e.g:
    ## pullSecrets:
    ##   - myRegistryKeySecretName
    ##
    pullSecrets: [ ]

  ##
  ##
  auth:
    ##
    ##
    username: admin
    ##
    ##
    password: "rU40Fm%0GnK£iqQN"

  ##
  ##
  service:
    ##
    ##
    api:
      ##
      ##
      type: ClusterIP
      ##
      ##
      annotations: { }
    ##
    ##
    main:
      ##
      ##
      type: ClusterIP
      ##
      ##
      annotations: { }
  ##
  ##
  persistence:
    ##
    ##
    size: 500Mi
    ##
    ##
    accessModes:
      - ReadWriteOnce
  ##
  ##
  updateStrategy:
    ##
    ##
    type: RollingUpdate
  ##
  ##
  envFrom: [ ]
  ##
  ##
  env: [ ]
  ##
  ##
  volumes: [ ]
  ##
  ##
  volumeMounts: [ ]
  ##
  ##
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi

worker:
  ##
  ##
  additionalAnnotations: { }
  ##
  ##
  additionalLabels: { }
  ##
  ##
  replicaCount: 2
  ##
  ##
  updateStrategy:
    type: RollingUpdate
  ##
  ##
  nameOverride: ""
  ##
  ##
  image:
    ##
    ##
    registry: docker.io
    ##
    ##
    repository: wazuh/wazuh-manager
    ##
    ##
    tag: '{{ .Values.global.version }}'
    ##
    ##
    digest: ""
    ## Specify a imagePullPolicy
    ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
    ## ref: https://kubernetes.io/docs/concepts/containers/images/#pre-pulled-images
    ##
    pullPolicy: IfNotPresent
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ## e.g:
    ## pullSecrets:
    ##   - myRegistryKeySecretName
    ##
    pullSecrets: [ ]

  ##
  ##
  volumeMounts: [ ]

  ##
  ##
  initContainers: [ ]
  ##
  ##
  env: [ ]
  ##
  ##
  envFrom: [ ]
  ##
  ##
  volumes:
    - name: manager-backup
      persistentVolumeClaim:
        claimName: '{{ include "common.names.fullname" $ }}-manager-backup'
  ##
  ##
  podManagementPolicy: Parallel
  ##
  ##
  service:
    ##
    ##
    type: ClusterIP
    ##
    ##
    additionalLabels: { }
    ##
    ##
    annotations: { }
    ##
    ##
    loadBalancerClass: ""
    ##
    ##
    port: 1514

  ##
  ##
  persistence:
    ##
    ##
    size: 200Mi
    ##
    ##
    accessModes:
      - ReadWriteOnce

  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi

master:
  replicaCount: 1
  ##
  ##
  nameOverride: ""
  ##
  ##
  image:
    registry: docker.io
    repository: wazuh/wazuh-manager
    tag: '{{ .Values.global.version }}'
    digest: ""
    ## Specify a imagePullPolicy
    ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
    ## ref: https://kubernetes.io/docs/concepts/containers/images/#pre-pulled-images
    ##
    pullPolicy: IfNotPresent
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ## e.g:
    ## pullSecrets:
    ##   - myRegistryKeySecretName
    ##
    pullSecrets: [ ]
  ##
  ##
  service:
    ##
    ##
    type: ClusterIP
    ##
    ##
    additionalLabels: { }
    ##
    ##
    annotations: { }
    ##
    ##
    loadBalancerClass: ""
    ##
    ##
    port: 1515
  ##
  ##
  additionalAnnotations: { }
  ##
  ##
  additionalLabels: { }
  ##
  ##
  persistence:
    ##
    ##
    size: 200Mi
    ##
    ##
    backupSize: 200Mi
    ##
    ##
    accessModes:
      - ReadWriteOnce

  ##
  ##
  ingress:
    ##
    ##
    enabled: false
    ##
    ##
    name: "wazuh-master"
    ##
    ##
    className: ""
    ##
    ##
    annotations: { }
    ##
    ##
    host: "{{ .Values.global.domain }}"
    ##
    ##
    tls: true

    additionalLabels: { }

  ##
  ##
  podManagementPolicy: Parallel

  ##
  ##
  updateStrategy:
    type: RollingUpdate
  ##
  initContainers:
    - name: permission-fix
      image: busybox
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 100m
          memory: 256Mi
      command:
        - /bin/sh
        - -c
        - |
          set -ex
          # Change owner of the common directories
          chown -R 1000:1000 /var/lib/backup
          chown -R 1000:1000 /var/lib/snort
          chown -R 1000:1000 /var/lib/owasp-zap
      volumeMounts:
        - name: manager-backup
          mountPath: /var/lib/backup
        - name: snort-alerts
          mountPath: /var/lib/snort
        - name: owasp-zap-alerts
          mountPath: /var/lib/owasp-zap
  ##
  ##
  env: [ ]
  ##
  ##
  envFrom: [ ]
  ##
  ##
  volumes:
    - name: manager-backup
      persistentVolumeClaim:
        claimName: '{{ include "common.names.fullname" $ }}-manager-backup'
    - name: snort-alerts
      persistentVolumeClaim:
        claimName: snort-alerts
    - name: owasp-zap-alerts
      persistentVolumeClaim:
        claimName: owasp-zap-alerts

  volumeMounts:
    - name: snort-alerts
      mountPath: /var/log/snort/
    - name: owasp-zap-alerts
      mountPath: /var/log/owasp-zap/

  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi

##
##
extraVolumeConfigs:
  - name: '{{ include "common.names.fullname" $ }}-manager-backup'
    additionalAnnotations: { }
    additionalLabels: { }
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: '{{ $.Values.master.persistence.backupSize }}'
  - name: snort-alerts
    additionalAnnotations: { }
    additionalLabels: { }
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 200Mi
  - name: owasp-zap-alerts
    additionalAnnotations: { }
    additionalLabels: { }
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 200Mi

##
##
dashboard:
  ##
  ##
  nameOverride: ""
  ##
  ##
  image:
    ##
    ##
    registry: docker.io
    ##
    ##
    repository: wazuh/wazuh-dashboard
    tag: '{{ .Values.global.version }}'
    digest: ""
    ## Specify a imagePullPolicy
    ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
    ## ref: https://kubernetes.io/docs/concepts/containers/images/#pre-pulled-images
    ##
    pullPolicy: IfNotPresent
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ## e.g:
    ## pullSecrets:
    ##   - myRegistryKeySecretName
    ##
    pullSecrets: [ ]

  ##
  ##
  additionalAnnotations: { }
  additionalLabels: { }
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  service:
    additionalLabels: { }
    ##
    ##
    type: ClusterIP # LoadBalancer
    ##
    ##
    port: 5601
    ##
    ##
    targetPort: 5601
    ##
    ##
    annotations: { }
    ##
    ##
    loadBalancerIP: null
    ##
    ##
    allocateLoadBalancerNodePorts: null
    ##
    ##
    clusterIP: null
  ##
  ##
  auth:
    ##
    ##
    username: kibanaserver
    ##
    ##
    password: "mS05mw_0a?-nMGfM"
  ##
  ##
  ingress:
    ##
    ##
    additionalLabels: { }
    ##
    ##
    enabled: false
    ##
    ##
    name: "wazuh-dashboard"
    ##
    ##
    className: ""
    ##
    ##
    annotations: { }
    ##
    ##
    host: "{{ .Values.global.domain }}"
  ports:
    - containerPort: 5601
      name: dashboard
  volumes: [ ]
  volumeMounts: [ ]
  env: [ ]
  envFrom: [ ]


service:
  ##
  ##
  type: ClusterIP
  ##
  ##
  additionalLabels: { }
  ##
  ##
  annotations: { }
  ##
  ##
  loadBalancerClass: ""

cluster:
  auth:
    key: "dfbb2c1b9d679c39af94d5c1c821c952"
  config:
    smtp:
      server: smtp.example.wazuh.com
      from: ossecm@example.wazuh.com
      to: recipient@example.wazuh.com
      max_per_hour: 12