storageClass:
  provisioner: microk8s.io/hostpath
  volumeBindingMode: WaitForFirstConsumer
  reclaimPolicy: Delete

dashboard:
  service:
    type: LoadBalancer

master:
  service:
    type: LoadBalancer
  resources:
    requests:
      memory: 1Gi
    limits:
      memory: 2Gi
worker:
  replicaCount: 1
  resources:
    requests:
      memory: 1Gi
    limits:
      memory: 2Gi
indexer:
  replicas: 2
  resources:
    requests:
      memory: 1Gi
    limits:
      memory: 2Gi