{{- range .Values.configmaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.tplvalues.render" (dict "value" .name "context" $) }}
  namespace: {{ include "common.names.namespace" $ }}
  annotations:
    {{- include "common.annotations.standard" ( dict "customAnnotations" .additionalAnnotations "context" $ ) | nindent 4 }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .additionalLabels "context" $ ) | nindent 4 }}
{{ with .data }}
data:
{{- range $k, $v := . }}
  {{- $f := include "common.tplvalues.render" (dict "value" $v "context" $) -}}
  {{ $k | quote | nindent 2 }} : {{ include "common.tplvalues.render" (dict "value" $f "context" $) | quote }}
{{- end }}
{{- end }}
{{ with .immutable }}
immutable: {{ include "common.tplvalues.render" (dict "value" . "context" $) }}
{{- end }}
{{ with .binaryData }}
binaryData: {{ include "common.tplvalues.render" (dict "value" . "context" $) | nindent 2}}
{{- end }}
---
{{- end }}
