{{ range .Values.rolebindings }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  {{ with .name }}
  name: {{ include "common.tplvalues.render" (dict "value" . "context" $) }}
  {{ end }}
  namespace: {{ .namespace | default (include "common.names.namespace" $) }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .additionalLabels "context" $ ) | nindent 4 }}
  annotations:
    {{- include "common.annotations.standard" ( dict "customAnnotations" .additionalAnnotations "context" $ ) | nindent 4 }}
{{ with .subjects -}}
subjects: {{ include "common.tplvalues.render" (dict "value" . "context" $) | nindent 2 }}
{{- end }}
{{ with .roleRef -}}
roleRef: {{ include "common.tplvalues.render" (dict "value" . "context" $) | nindent 2 }}
{{- end }}
---
{{ end }}