apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: {{ include "common.names.fullname" $ }}-trigger
  namespace: {{ include "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  annotations:
    {{- include "common.annotations.standard" ( dict "customAnnotations" .Values.commonAnnotations "context" $ ) | nindent 4 }}
spec:
  template:
    ref: {{ include "common.names.fullname" $ }}-template