apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" $ }}-wazuh-conf
data:
  "template.config.conf": {{ $.Files.Get "files/configs/template.config.conf.xml" | quote }}
  "local_rules.xml": {{ $.Files.Get "files/configs/local_rules.xml" | quote }}
  "local_decoder.xml": {{ $.Files.Get "files/configs/local_decoder.xml" | quote }}
  "0004-owasp-zap.xml": {{ $.Files.Get "files/configs/owasp_zap_decoder.xml" | quote }}
  "wazuh.replace-var.sh": {{ $.Files.Get "files/scripts/wazuh.replace-var.sh" | quote }}