{{- with .Values.secretjob }}
{{- if .enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common.names.fullname" $ }}-one-time-job
  namespace: {{ include "common.names.namespace" $ }}
  annotations:
    "helm.sh/hook-weight": "4"
    {{ include "common.annotations.standard" ( dict "customAnnotations" .additionalAnnotations "context" $ ) | nindent 4 }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .additionalLabels "context" $ ) | nindent 4 }}
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: {{ include "common.names.fullname" $ }}-job-secret
      restartPolicy: Never
      volumes:
        - name: certificates
          emptyDir: { }
        - name: scripts
          configMap:
            name: {{ include "common.names.fullname" $ }}-job-secret-script
        - name: root-ca-certs
          secret:
            secretName: {{ include "wazuh.cert_root_name" $ }}
      initContainers:
        - name: cert-generator
          {{ $imageTpl := include "common.images.image" (dict "imageRoot" .image "global" $.Values.global) }}
          image: {{ include "common.tplvalues.render" (dict "value" $imageTpl "context" $) | quote }}
          volumeMounts:
            - mountPath: /certificates
              name: certificates
            - mountPath: /scripts/gen_certs.sh
              name: scripts
              subPath: gen_certs.sh
              readOnly: true
            - mountPath: /root-certs
              name: root-ca-certs
              readOnly: true
          command:
            - /bin/sh
            - -c
            - |
              set -ex

              # Install openssl and bash
              apk add --no-cache openssl bash

              # Copy root CA certificates to a tmp folder
              export ROOT_CA_FOLDER=$(mktemp -d)
              cp /root-certs/* $ROOT_CA_FOLDER

              # Generate certificates
              /bin/bash /scripts/gen_certs.sh /certificates

              # Adjust file permissions to be readable by other users
              chmod -R 775 /certificates/*
      containers:
        - name: secret-creator
          {{ $secretImageTpl := include "common.images.image" (dict "imageRoot" .secretImage "global" $.Values.global) }}
          image: {{ include "common.tplvalues.render" (dict "value" $secretImageTpl "context" $) | quote }}
          volumeMounts:
            - mountPath: /certificates
              name: certificates
          command:
            - /bin/sh
            - -c
            - |
              set -ex

              echo "Creating secret from certificates folder..."
              SECRET_NAME={{ include "wazuh.cert_secret_name" $ }}
              NAMESPACE={{ include "common.names.namespace" $ }}
              TEMP_DIR="/certificates/"

              echo "Listing files in $TEMP_DIR"
              ls -la $TEMP_DIR

              echo "Check if directory exists"
              if [ -d "$TEMP_DIR" ]; then
                echo "Build the kubectl command dynamically"
                kubectl create secret generic $SECRET_NAME --from-file=$TEMP_DIR -n $NAMESPACE || true
                echo "Secret $SECRET_NAME created successfully."
              else
                echo "Directory $TEMP_DIR does not exist or is empty!"
                exit 1
              fi
{{- end }}
{{- end }}