global: 
  discord_webhook_url: "<your-url-here>"

prom-stack: 
  alertmanager:
    tplConfig: true
    config:
      route:
        receiver: "discord"
        group_by:
          - namespace
        continue: false
        routes:
          - receiver: "discord"
            matchers:
              - alertname="Watchdog"
            continue: false
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 12h
      receivers:
        - name: discord
          discord_configs:
            - webhook_url: "{{ $.Values.global.discord_webhook_url }}"