prom-stack:
  alertmanager:
    alertmanagerSpec:
      storage:
        volumeClaimTemplate:
          spec:
            resources:
              requests:
                storage: 50Gi
                
  grafana:
    ingress:
      enabled: true
      ingressClassName: alb
      annotations:
        alb.ingress.kubernetes.io/load-balancer-name: '{{ include "common.names.fullname" $ }}-grafana'
        alb.ingress.kubernetes.io/backend-protocol: 'HTTPS'
        alb.ingress.kubernetes.io/target-type: 'ip'
        alb.ingress.kubernetes.io/scheme: 'internet-facing'
        alb.ingress.kubernetes.io/listen-ports: |
          [
            {
              "HTTP": 80
            },
            {
              "HTTPS": 443
            }
          ]
        alb.ingress.kubernetes.io/actions.forward-single: |
          {
            "Type": "forward",
            "ForwardConfig": {
              "TargetGroups": [
                {
                  "ServiceName": "{{ include "common.names.fullname" . }}",
                  "ServicePort": "80"
                }
              ]
            }
          }
        alb.ingress.kubernetes.io/ssl-redirect: '443'
        external-dns.alpha.kubernetes.io/hostname: '{{ .Values.global.domain }}'
