global:
  storageClassName: ~
  domain: 'grafana.example.team'

## @param kubeVersion Override Kubernetes version
##
kubeVersion: ""
## @param nameOverride String to partially override common.names.fullname template (will maintain the release name)
##
nameOverride: ""
## @param fullnameOverride String to fully override common.names.fullname template
##
fullnameOverride: ""
## @param commonLabels Labels to add to all deployed resources
##
commonLabels: { }

commonAnnotations:
  "kubernetes.io/description": '{{ include "common.names.fullname" $ }} monitoring'

##
##
storageClasses:
  '{{ include "common.storage-className" $ }}':
    ##
    ##
    enabled: true
    ##
    ##
    additionalAnnotations: { }
    ##
    ##
    additionalLabels: { }
    ##
    ##
    provisioner: ""
    ##
    ##
    parameters: { }
    ##
    ##
    volumeBindingMode: ""
    ##
    ##
    reclaimPolicy: Delete

keycloak:
  enabled: true
  client_id: "grafana"
  client_secret: "some-secret"
  url: "https://keycloak.example.me"
  realm: "demo"

prom-stack:
  alertmanager:
    alertmanagerSpec:
      logLevel: error
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: '{{ include "common.storage-className" $ }}'
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 10Gi

  prometheus:
    prometheusSpec:
      retention: 10d
      logLevel: error
      securityContext:
        runAsGroup: 0
        runAsNonRoot: false
        runAsUser: 0
        fsGroup: 0
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: '{{ include "common.storage-className" $ }}'
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 10Gi

  grafana:
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.middlewares: oauth2-secured-oauth2@kubernetescrd
      hosts:
        - "{{ .Values.global.domain }}"
    sidecar:
      datasources:
        enabled: true
        label: grafana_datasource
        isDefaultDatasource: false
        defaultDatasourceEnabled: false
    plugins:
      - grafana-piechart-panel
      - grafana-clock-panel
    enabled: true
    envFromSecret: '{{ $.Release.Name }}-keycloak-conf'
    grafana.ini:
      server:
        root_url: "https://{{ .Values.global.domain }}"
        enable_gzip: true
      auth:
        disable_login_form: true
      auth.basic:
        enabled: false
      auth.generic_oauth:
        enabled: "true"
        name: "Example login"
        allow_sign_up: "true"
        client_id: '$__env{KEYCLOAK_CLIENT_ID}'
        client_secret: '$__env{KEYCLOAK_CLIENT_SECRET}'
        scopes: "openid email profile offline_access roles"
        email_attribute_path: "email"
        login_attribute_path: "username"
        name_attribute_path: "full_name"
        auth_url: "$__env{KEYCLOAK_ISSUER}/protocol/openid-connect/auth"
        token_url: "$__env{KEYCLOAK_ISSUER}/protocol/openid-connect/token"
        api_url: "$__env{KEYCLOAK_ISSUER}/protocol/openid-connect/userinfo"
        role_attribute_path: "contains(roles[*], 'admin') && 'Admin' || contains(roles[*], 'editor') && 'Editor' || 'Viewer'"

loki:
  enabled: true
  loki:
    commonConfig:
      replication_factor: 1
    schemaConfig:
      configs:
        - from: "2024-04-01"
          store: tsdb
          object_store: s3
          schema: v13
          index:
            prefix: loki_index_
            period: 24h
    pattern_ingester:
      enabled: true
    limits_config:
      allow_structured_metadata: true
      volume_enabled: true
    ruler:
      enable_api: true

  minio:
    enabled: true

  deploymentMode: SingleBinary

  singleBinary:
    replicas: 1

  # Zero out replica counts of other deployment modes
  backend:
    replicas: 0
  read:
    replicas: 0
  write:
    replicas: 0

  ingester:
    replicas: 0
  querier:
    replicas: 0
  queryFrontend:
    replicas: 0
  queryScheduler:
    replicas: 0
  distributor:
    replicas: 0
  compactor:
    replicas: 0
  indexGateway:
    replicas: 0
  bloomCompactor:
    replicas: 0
  bloomGateway:
    replicas: 0
    
alloy:
  enabled: true
  alloy: 
    configMap: 
      content: |-
        logging {
          level  = "info"
          format = "logfmt"
        }
          
        discovery.kubernetes "pods" {
          role = "pod"
        }
          
        discovery.kubernetes "nodes" {
          role = "node"
        }
          
        discovery.kubernetes "services" {
          role = "service"
        }
          
        discovery.kubernetes "endpoints" {
          role = "endpoints"
        }
          
        discovery.kubernetes "endpointslices" {
          role = "endpointslice"
        }
          
        discovery.kubernetes "ingresses" {
          role = "ingress"
        }
        
        loki.write "default" {
          endpoint {
            url = "http://{{ .Release.Name }}-loki:3100/loki/api/v1/push"
          }
        }