{{ with .Values.cluster -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" $ }}-common-config
stringData:
  SMTP_SERVER: "{{ .config.smtp.server }}"
  SMTP_FROM: "{{ .config.smtp.from }}"
  SMTP_TO: "{{ .config.smtp.to }}"
  SMTP_MAX_PER_HOUR: "{{ .config.smtp.max_per_hour }}"
  QUEUE_SIZE: '131072'
  AGENTS_DISCONNECTION_TIME: '20s'
  AGENTS_DISCONNECTION_ALERT_TIME: '100s'

  INDEXER_URL: 'https://{{ include "common.names.fullname" $ }}-indexer-api:9200'

  CLUSTER_NAME: '{{ include "common.names.fullname" $ }}'
  CLUSTER_NODE_NAME: '{{ include "common.names.fullname" $ }}-master-0.{{ include "common.names.fullname" $ }}-cluster'
{{- end }}