{{ with .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" $ }}
  namespace: {{ include "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .additionalLabels "context" $ ) | nindent 4 }}
    app: {{ include "common.names.fullname" $ }}-manager
  annotations:
    {{- include "common.annotations.standard" ( dict "customAnnotations" .annotations "context" $ ) | nindent 4 }}
spec:
  {{ with .type }}
  type: {{ include "common.tplvalues.render" (dict "value" . "context" $) }}
  {{ end }}
  {{ if eq .type "LoadBalancer" }}
  {{ with .loadBalancerClass }}
  loadBalancerClass: {{ include "common.tplvalues.render" (dict "value" . "context" $) }}
  {{ end }}
  {{ end }}
  selector:
    {{- include "common.labels.matchLabels" ( dict "customLabels" .additionalLabels "context" $ ) | nindent 4 }}
    app: {{ include "common.names.fullname" $ }}-manager
  ports:
    - name: agents-events
      port: {{ $.Values.worker.service.port }}
      targetPort: agents-events
      protocol: TCP
    - name: registration
      port: {{ $.Values.master.service.port }}
      targetPort: registration
      protocol: TCP
{{- end -}}