apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" $ }}-indexer-conf
data:
  "opensearch.yml": {{ $.Files.Get "files/configs/opensearch.yml" | quote }}
  "internal_users.yml": {{ $.Files.Get "files/configs/internal_users.yml" | quote }}