{{ with .Values.indexer.auth -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" $ }}-indexer-cred
type: kubernetes.io/basic-auth
stringData:
  INDEXER_USERNAME: '{{ .username }}'
  INDEXER_PASSWORD: '{{ .password }}'
{{- end }}