{{- if and .Values.indexer.service .Values.indexer.service.main -}}
{{ with .Values.indexer.service.main }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" $ }}-indexer
  namespace: {{ include "common.names.namespace" $ }}
  annotations:
    {{- include "common.annotations.standard" ( dict "customAnnotations" .annotations "context" $ ) | nindent 4 }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .additionalLabels "context" $ ) | nindent 4 }}
    app: {{ include "common.names.fullname" $ }}-indexer
spec:
  selector:
    {{- include "common.labels.matchLabels" ( dict "customLabels" .additionalLabels "context" $ ) | nindent 4 }}
    app: {{ include "common.names.fullname" $ }}-indexer
  ports:
    - name: indexer-nodes
      port: 9300
      targetPort: 9300
  clusterIP: None
{{- end -}}
{{- end -}}