{{ with .Values.indexer.auth -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secret.indexer-auth" $ }}
  annotations:
    {{- include "common.annotations.standard" ( dict "customAnnotations" .additionalAnnotations "context" $ ) | nindent 4 }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .additionalLabels "context" $ ) | nindent 4 }}
stringData:
  INDEXER_USERNAME: '{{ .username }}'
  INDEXER_PASSWORD: '{{ .password }}'
{{- end }}