{{ with .Values.apiCred.auth -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" $ }}-api-cred
stringData:
  API_USERNAME: '{{ .username }}'
  API_PASSWORD: '{{ .password }}'
{{- end }}