{{- with .Values.secretjob }}
{{- if .enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "common.names.fullname" $ }}-secret-manager-role
  namespace: {{ include "common.names.namespace" $ }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
{{- end }}
{{- end }}