{{- with .Values.secretjob }}
{{- if .enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "common.names.fullname" $ }}-secret-manager-binding
  namespace: {{ include "common.names.namespace" $ }}
  annotations:
    "helm.sh/hook-weight": "3"
    {{- include "common.annotations.standard" ( dict "customAnnotations" .additionalAnnotations "context" $ ) | nindent 4 }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .additionalLabels "context" $ ) | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "common.names.fullname" $ }}-job-secret
    namespace: {{ include "common.names.namespace" $ }}
roleRef:
  kind: Role
  name: {{ include "common.names.fullname" $ }}-secret-manager-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}