{{- range $k, $v := .Values.secrets }}
{{ if $v.enabled }}
{{ with $v }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.tplvalues.render" (dict "value" $k "context" $) }}
  namespace: {{ include "common.names.namespace" $ }}
  annotations:
    {{- include "common.annotations.standard" ( dict "customAnnotations" .additionalAnnotations "context" $ ) | nindent 4 }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .additionalLabels "context" $ ) | nindent 4 }}
{{ with .type }}
type: {{ include "common.tplvalues.render" (dict "value" . "context" $) }}
{{- end }}
{{ with .immutable }}
immutable: {{ include "common.tplvalues.render" (dict "value" . "context" $) }}
{{- end }}
{{ with .data }}
data:
{{- range $k, $v := . }}
  {{- $f := include "common.tplvalues.render" (dict "value" $v "context" $) -}}
  {{ $k | quote | nindent 2 }} : {{ include "common.tplvalues.render" (dict "value" $f "context" $) | quote }}
{{- end }}
{{- end }}
{{ with .stringData -}}
stringData:
{{- range $k, $v := . -}}
  {{- $f := include "common.tplvalues.render" (dict "value" $v "context" $) -}}
  {{ $k | quote | nindent 2 }} : {{ include "common.tplvalues.render" (dict "value" $f "context" $) | quote }}
{{- end }}
{{- end }}
---
{{- end -}}
{{- end -}}
{{- end }}
