apiVersion: v1
kind: Service
metadata:
  annotations:
    kubernetes.io/description: wazuh cluster
  labels:
    app: wazuh-manager
    app.kubernetes.io/instance: wazuh
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: wazuh
    app.kubernetes.io/version: 4.9.2
    argocd.argoproj.io/instance: wazuh
    helm.sh/chart: wazuh-helm-0.2.17
  name: wazuh-master
  namespace: wazuh
spec:
  ports:
    - name: cluster
      port: 1516
      protocol: TCP
      targetPort: 1516
  clusterIP: None
  selector:
    app: wazuh-manager
    app.kubernetes.io/instance: wazuh
    app.kubernetes.io/name: wazuh
