storageClass:
  provisioner: efs.csi.aws.com
  parameters:
    basePath: /wazuh-data
    directoryPerms: '775'
    fileSystemId: '<fileSystemId>'
    uid: '0'
    gid: '0'
    provisioningMode: efs-ap
  reclaimPolicy: Retain