storageClasses:
  '{{ include "wazuh.storageClassName" $ }}':
    provisioner: rancher.io/local-path
    volumeBindingMode: WaitForFirstConsumer

dashboard:
  ingress:
    enabled: true
    className: traefik