  indexer:
    image:
      registry: ghcr.io
      repository: adorsys-gis/wazuh-indexer-s3
      tag: release-candidate-indexer-snapshots-c3dbb18
    s3Snapshot:
      enabled: true
      credentialsSecret: aws-s3-credentials
      repository: "s3-repo"
      s3Settings:
        bucket: "wazuh-dev-backup"
        region: "eu-central-1"
        basePath: "snapshots"
      register:
        enabled: true
      cronjob:
        enabled: true
      cleanup:
        enabled: true

