storageClass:
  provisioner: efs.csi.aws.com
  parameters:
    basePath: /wazuh-data
    directoryPerms: '775'
    fileSystemId: '<fileSystemId>'
#    uid: '1000'
#    gid: '1000'
    provisioningMode: efs-ap
  reclaimPolicy: Retain