storageClasses:
  '{{ include "wazuh.storageClassName" $ }}':
    enabled: false
  '{{ include "common.names.fullname" $ }}-efs':
    enabled: true
    provisioner: efs.csi.aws.com
    parameters:
      basePath: /wazuh-data
      directoryPerms: '775'
      fileSystemId: '<fileSystemId>'
      uid: '0'
      gid: '0'
      provisioningMode: efs-ap
    reclaimPolicy: Retain

extraVolumeConfigs:
  '{{ include "common.names.fullname" $ }}-manager-backup':
    storageClassName: '{{ include "common.names.fullname" $ }}-efs'
    accessModes:
      - ReadWriteMany
  snort-alerts:
    storageClassName: '{{ include "common.names.fullname" $ }}-efs'
    accessModes:
      - ReadWriteMany
  owasp-zap-alerts:
    storageClassName: '{{ include "common.names.fullname" $ }}-efs'
    accessModes:
      - ReadWriteMany