storageClasses:
  provisioner: microk8s.io/hostpath
  volumeBindingMode: WaitForFirstConsumer
  reclaimPolicy: Delete

dashboard:
  service:
    type: LoadBalancer
  resources: ~

master:
  service:
    type: LoadBalancer
  resources: ~
worker:
  replicaCount: 1
  resources: ~
indexer:
  replicas: 2
  resources: ~