storageClasses:
  provisioner: microk8s.io/hostpath
  volumeBindingMode: WaitForFirstConsumer
  reclaimPolicy: Delete

svcs:
  '{{ include "common.names.fullname" $ }}-dashboard':
    type: LoadBalancer

dashboard:
  resources: ~

master:
  resources: ~
worker:
  replicaCount: 1
  resources: ~
indexer:
  replicas: 2
  resources: ~