# This should be installed by default by the loki helm chart
# But it is here just for reference
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "common.names.fullname" . }}-datasources
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" $ | nindent 4 }}
    grafana_datasource: "1"

data:
  datasource.yml: |-
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        orgId: 1
        access: proxy
        url: http://loki:3100
        basicAuth: false
      - name: prometheus
        type: prometheus
        orgId: 1
        access: proxy
        url: http://{{ .Release.Name }}-prom-stack-prometheus:9090
        basicAuth: false
      - name: alertmanager
        type: alertmanager
        orgId: 1
        access: proxy
        url: http://{{ .Release.Name }}-prom-stack-alertmanager:9093
        basicAuth: false
        jsonData:
          implementation: prometheus
