{{ with .Values.keycloak }}
{{- if .enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-keycloak-conf
  annotations:
    {{- include "common.annotations.standard" ( dict "customAnnotations" $.Values.commonAnnotations "context" $ ) | nindent 4 }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" $.Values.commonLabels "context" $ ) | nindent 4 }}
stringData:
  KEYCLOAK_CLIENT_ID: "{{ include "common.tplvalues.render" (dict "value" .client_id "context" $) }}"
  KEYCLOAK_CLIENT_SECRET: "{{ include "common.tplvalues.render" (dict "value" .client_secret "context" $) }}"
  KEYCLOAK_ISSUER: "{{ include "common.tplvalues.render" (dict "value" .url "context" $) }}/realms/{{ include "common.tplvalues.render" (dict "value" .realm "context" $) }}"

{{- end -}}
{{ end }}
