{{- if eq (include "integration.azure.exists" $) "true" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secret.common" $ }}-azure
  annotations:
    {{- include "common.annotations.standard" ( dict "customAnnotations" .additionalAnnotations "context" $ ) | nindent 4 }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .additionalLabels "context" $ ) | nindent 4 }}
stringData:
  {{ if (eq (include "integration.azure.exists.log" $) "true") -}}
  {{ with .Values.integration.azure.auth.log }}
  log_auth: |
    application_id: {{ include "common.tplvalues.render" (dict "value" .application_id "context" $) }}
    application_key: {{ include "common.tplvalues.render" (dict "value" .application_key "context" $) }}
  {{- end -}}
  {{ end }}

  {{ if (eq (include "integration.azure.exists.graph" $) "true") -}}
  {{- with .Values.integration.azure.auth.graph -}}
  graph_auth: |
    application_id: {{ include "common.tplvalues.render" (dict "value" .application_id "context" $) }}
    application_key: {{ include "common.tplvalues.render" (dict "value" .application_key "context" $) }}
  {{- end -}}
  {{- end }}

  {{ if (eq (include "integration.azure.exists.storage" $) "true") -}}
  {{- with .Values.integration.azure.auth.storage -}}
  storage_auth: |
    account_name: {{ include "common.tplvalues.render" (dict "value" .account_name "context" $) }}
    account_key: {{ include "common.tplvalues.render" (dict "value" .account_key "context" $) }}
  {{- end -}}
  {{- end }}
{{- end -}}