{{ with .Values.notification.slack -}}
{{- if and .enabled (not .externalSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secret.notification-slack" $ }}
  annotations:
    {{- include "common.annotations.standard" ( dict "customAnnotations" .additionalAnnotations "context" $ ) | nindent 4 }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .additionalLabels "context" $ ) | nindent 4 }}
stringData:
  SLACK_CONFIG: |
    <integration>
        <name>slack</name>
        <hook_url>{{ include "common.tplvalues.render" (dict "value" .webhookUrl "context" $) }}</hook_url>
        <alert_format>json</alert_format>
    </integration>

{{- end -}}
{{- end }}