{{- if and .Values.master .Values.master.backup .Values.master.backup.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "common.names.fullname" $ }}-manager-backup
  namespace: {{ include "common.names.namespace" $ }}
  annotations:
    {{- include "common.annotations.standard" ( dict "customAnnotations" (dict) "context" $ ) | nindent 4 }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" (dict) "context" $ ) | nindent 4 }}
{{- end }}
