master:
  resources:
    requests:
      memory: 2Gi
    limits:
      memory: 4Gi
worker:
  resources:
    requests:
      memory: 2Gi
    limits:
      memory: 4Gi
indexer:
  resources:
    requests:
      memory: 2Gi
    limits:
      memory: 4Gi