storageClass:
  provisioner: rancher.io/local-path
  volumeBindingMode: WaitForFirstConsumer

dashboard:
  service:
    type: LoadBalancer

master:
  service:
    type: LoadBalancer
  resources:
    requests:
      memory: 2Gi
    limits:
      memory: 4Gi
worker:
  resources:
    requests:
      memory: 2Gi
    limits:
      memory: 4Gi
indexer:
  resources:
    requests:
      memory: 2Gi
    limits:
      memory: 4Gi