_meta:
  type: "rolesmapping"
  config_version: 2

all_access:
  reserved: false
  hidden: false
  backend_roles:
    - "wazuh_admin"
    
readall:
  reserved: false
  hidden: false
  backend_roles:
    - "wazuh_viewer"
  