apiVersion: batch/v1
kind: CronJob
metadata:
  name: wazuh-backup-trigger-cronjob
  namespace: wazuh
spec:
  schedule: "*/5 * * * *"  # Adjust schedule for 
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: backup-job-sa
          restartPolicy: Never
          containers:
            - name: trigger
              image: curlimages/curl:8.0.1
              command: ["/bin/sh", "-c"]
              args:
                - |
                  # Post an empty JSON payload to the EventListener.
                  # Ensure the eventlistener service is accessible from this job.
                  curl -X POST http://wazuh-backup-eventlistener.wazuh.svc.cluster.local:8080/ -H "Content-Type: application/json" -d '{}'
