# templates/eventlistener.yaml
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: wazuh-backup-eventlistener
  namespace: wazuh
spec:
  serviceAccountName: backup-job-sa
  triggers:
    - triggerRef: wazuh-backup-trigger
