{{- if .Values.backup.mode.triggers }}
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: {{ include "common.names.fullname" $ }}-listener
  namespace: {{ include "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  annotations:
    {{- include "common.annotations.standard" ( dict "customAnnotations" .Values.commonAnnotations "context" $ ) | nindent 4 }}
spec:
  serviceAccountName: {{ include "common.names.fullname" $ }}-sa
  triggers:
    {{- range $componentName, $config := .Values.backup.components }}
    {{- if $config.enabled }}
    - triggerRef: {{ include "common.names.fullname" $ }}-{{ $componentName }}-trigger
    {{- end }}
    {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" $ }}-listener-svc
  namespace: {{ include "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: eventlistener
  annotations:
    {{- include "common.annotations.standard" ( dict "customAnnotations" .Values.commonAnnotations "context" $ ) | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: {{ include "common.names.fullname" $ }}-listener
  ports:
    - name: http-listener
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: ClusterIP
{{- end }}
