apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: wazuh-backup-pipeline
  namespace: {{ .Values.namespace }}
spec:
  workspaces:
    - name: manager-data
    - name: indexer-shard0
    - name: indexer-shard1
    - name: backup-output
  params:
    - name: bucket
      type: string
      description: S3 bucket name
      default: {{ .Values.aws.bucket | quote }}
    - name: region
      type: string
      description: AWS region
      default: {{ .Values.aws.region | quote }}
  tasks:
    - name: prepare-manager
      taskRef:
        name: prepare-manager
      workspaces:
        - name: manager-data
          workspace: manager-data
        - name: backup-output
          workspace: backup-output

    - name: prepare-indexer
      runAfter: [prepare-manager]
      taskRef:
        name: prepare-indexer
      workspaces:
        - name: indexer-shard0
          workspace: indexer-shard0
        - name: indexer-shard1
          workspace: indexer-shard1
        - name: backup-output
          workspace: backup-output

    - name: upload-backups
      runAfter: [prepare-indexer]
      taskRef:
        name: upload-backups
      workspaces:
        - name: backup-output
          workspace: backup-output
      params:
        - name: bucket
          value: $(params.bucket)
        - name: region
          value: $(params.region)
