apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: wazuh-backup-pipeline-run-test
  namespace: {{ .Values.namespace }}
spec:
  serviceAccountName: wazuh-backup-sa
  pipelineRef:
    name: wazuh-backup-pipeline
  workspaces:
    - name: manager-data
      persistentVolumeClaim:
        claimName: {{ .Values.pvc.manager }}
    - name: indexer-shard0
      persistentVolumeClaim:
        claimName: {{ .Values.pvc.indexerShard0 }}
    - name: indexer-shard1
      persistentVolumeClaim:
        claimName: {{ .Values.pvc.indexerShard1 }}
    - name: backup-output
      emptyDir: {}
  params:
    - name: bucket
      value: {{ .Values.aws.bucket | quote }}
    - name: region
      value: {{ .Values.aws.region | quote }}
