apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: test-wazuh-backup
  namespace: wazuh
spec:
  serviceAccountName: backup-job-sa
  pipelineRef:
    name: wazuh-backup-pipeline
  workspaces:
    - name: backup-volume
      emptyDir: {}
    - name: wazuh-master-volume
      emptyDir: {}
