apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.staging.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: backup-staging
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - {{ .Values.pvc.staging.accessMode }}
  {{- if .Values.pvc.staging.storageClass }}
  storageClassName: {{ .Values.pvc.staging.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.pvc.staging.size }}