# templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "common.names.fullname" $ }}-sa
  namespace: {{ include "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  annotations:
    {{- include "common.annotations.standard" ( dict "customAnnotations" .Values.commonAnnotations "context" $ ) | nindent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "common.names.fullname" $ }}-role
  namespace: {{ include "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  annotations:
    {{- include "common.annotations.standard" ( dict "customAnnotations" .Values.commonAnnotations "context" $ ) | nindent 4 }}
rules:
  # Allow reading PVCs
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list"]

  # Allow reading the AWS creds Secret
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["{{ .Values.aws.secretName }}"]
    verbs: ["get"]

  # Allow reading and patching all Wazuh StatefulSets
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    resourceNames:
      {{- range $componentName, $config := .Values.backup.components }}
      {{- if $config.enabled }}
      - {{ $config.statefulsetName }}
      {{- end }}
      {{- end }}
    verbs:
      - get
      - list
      - patch
      - update

  # Allow operations on the scale subresource for all components
  - apiGroups: ["apps"]
    resources: ["statefulsets/scale"]
    resourceNames:
      {{- range $componentName, $config := .Values.backup.components }}
      {{- if $config.enabled }}
      - {{ $config.statefulsetName }}
      {{- end }}
      {{- end }}
    verbs:
      - get
      - patch
      - update

  # Allow creating and managing CronJobs
  - apiGroups: ["batch"]
    resources: ["cronjobs"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]

  # Allow managing Jobs (created by CronJobs)
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "common.names.fullname" $ }}-rolebinding
  namespace: {{ include "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  annotations:
    {{- include "common.annotations.standard" ( dict "customAnnotations" .Values.commonAnnotations "context" $ ) | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "common.names.fullname" $ }}-sa
    namespace: {{ include "common.names.namespace" $ }}
roleRef:
  kind: Role
  name: {{ include "common.names.fullname" $ }}-role
  apiGroup: rbac.authorization.k8s.io