apiVersion: v1
kind: ServiceAccount
metadata:
  name: wazuh-backup-sa
  namespace: {{ .Values.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: wazuh-backup-role
  namespace: {{ .Values.namespace }}
rules:
  # Allow reading the manager/indexer PVCs
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list"]

  # Allow reading the AWS creds Secret
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["{{ .Values.aws.secretName }}"]
    verbs: ["get"]

  # Allow reading and patching the StatefulSet itself
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    resourceNames:
      - {{ .Values.manager.statefulsetName }}
    verbs:
      - get
      - list
      - patch
      - update

  # Allow operations on the scale subresource
  - apiGroups: ["apps"]
    resources: ["statefulsets/scale"]
    resourceNames:
      - {{ .Values.manager.statefulsetName }}
    verbs:
      - get
      - patch
      - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wazuh-backup-rolebinding
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: wazuh-backup-sa
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: wazuh-backup-role
  apiGroup: rbac.authorization.k8s.io
