apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: upload-backups
  namespace: {{ .Values.namespace }}
spec:
  workspaces:
    - name: backup-output
      description: Workspace containing the archives to upload
  params:
    - name: bucket
      type: string
      description: S3 bucket name
      default: {{ .Values.aws.bucket | quote }}
    - name: region
      type: string
      description: AWS region
      default: {{ .Values.aws.region | quote }}
  steps:
    - name: upload
      image: amazon/aws-cli:2.13.10
      envFrom:
        - secretRef:
            name: {{ .Values.aws.secretName }}
      script: |
        #!/bin/sh
        set -e
        ARCHIVE_DIR="$(workspaces.backup-output.path)/archive"
        for file in "$ARCHIVE_DIR"/*.tar.gz; do
          tries=0
          until aws s3 cp "$file" s3://$(params.bucket)/ --region $(params.region); do
            tries=$((tries+1))
            echo "Upload failed for $file, attempt $tries" >&2
            [ "$tries" -ge 3 ] && { echo "Giving up on $file" >&2; exit 1; }
            sleep 5
          done
        done
