apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: s3-upload-task
  namespace: wazuh
spec:
  workspaces:
    - name: backup-volume

  # define a result to hold our chosen backup folder
  results:
    - name: bkp-folder
      description: Path of the most recent backup folder
  stepTemplate:
    env:
      - name: AWS_ACCESS_KEY_ID
        value: "{{ .Values.aws.accessKeyId }}"
      - name: AWS_SECRET_ACCESS_KEY
        value: "{{ .Values.aws.secretAccessKey }}"
      - name: AWS_SESSION_TOKEN
        value: "{{ .Values.aws.sessionToken }}"
    volumeMounts:
      - name: backup-volume
        mountPath: /backup
  steps:
    - name: find-latest-backup
      image: custom-backup-image:latest
      imagePullPolicy: IfNotPresent
      script: |
        #!/bin/sh
        set -ex
        # pick the newest timestamped folder
        bkp=$(ls -td /backup/wazuh_files_backup/* | head -n 1)
        echo -n "$bkp" > $(results.bkp-folder.path)
        echo "Found latest backup: $bkp"

    - name: upload-to-s3
      image: custom-backup-image:latest
      script: |
        #!/bin/sh
        set -ex
        echo "Uploading backup folder: $(results.bkp-folder.path) to S3..."
        aws s3 sync \
          "$(results.bkp-folder.path)" \
          s3://test-wazuh-backup-bucket/$(basename "$(results.bkp-folder.path)")

