apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: prepare-indexer
  namespace: {{ .Values.namespace }}
spec:
  workspaces:
    - name: indexer-shard0
    - name: indexer-shard1
    - name: backup-output
  steps:
    - name: archive-indexer-shard0
      image: alpine:3.17
      script: |
        #!/bin/sh
        ts=$(date +'%Y%m%d%H%M')
        base_out=$(workspaces.backup-output.path)
        tmp0="$base_out/tmp-indexer0-$ts"
        mkdir -p "$tmp0"

        rsync -a \
          --relative \
          "$(workspaces.indexer-shard0.path)/etc/wazuh-indexer/certs/" \
          "$(workspaces.indexer-shard0.path)/etc/wazuh-indexer/jvm.options" \
          "$(workspaces.indexer-shard0.path)/etc/wazuh-indexer/jvm.options.d/" \
          "$(workspaces.indexer-shard0.path)/etc/wazuh-indexer/log4j2.properties" \
          "$(workspaces.indexer-shard0.path)/etc/wazuh-indexer/opensearch.yml" \
          "$(workspaces.indexer-shard0.path)/etc/wazuh-indexer/opensearch.keystore" \
          "$(workspaces.indexer-shard0.path)/etc/wazuh-indexer/opensearch-observability/" \
          "$(workspaces.indexer-shard0.path)/etc/wazuh-indexer/opensearch-reports-scheduler/" \
          "$(workspaces.indexer-shard0.path)/etc/wazuh-indexer/opensearch-security/" \
          "$(workspaces.indexer-shard0.path)/usr/lib/sysctl.d/wazuh-indexer.conf" \
          "$tmp0/"
        
        mkdir -p "$base_out/archive"
        tar czf "$base_out/archive/indexer-shard0-${ts}.tar.gz" -C "$base_out" "$(basename "$tmp0")"
        rm -rf "$tmp0"

    - name: archive-indexer-shard1
      image: alpine:3.17
      script: |
        #!/bin/sh
        ts=$(date +'%Y%m%d%H%M')
        base_out=$(workspaces.backup-output.path)
        tmp1="$base_out/tmp-indexer1-$ts"
        mkdir -p "$tmp1"

        rsync -a \
          --relative \
          "$(workspaces.indexer-shard1.path)/etc/wazuh-indexer/certs/" \
          "$(workspaces.indexer-shard1.path)/etc/wazuh-indexer/jvm.options" \
          "$(workspaces.indexer-shard1.path)/etc/wazuh-indexer/jvm.options.d/" \
          "$(workspaces.indexer-shard1.path)/etc/wazuh-indexer/log4j2.properties" \
          "$(workspaces.indexer-shard1.path)/etc/wazuh-indexer/opensearch.yml" \
          "$(workspaces.indexer-shard1.path)/etc/wazuh-indexer/opensearch.keystore" \
          "$(workspaces.indexer-shard1.path)/etc/wazuh-indexer/opensearch-observability/" \
          "$(workspaces.indexer-shard1.path)/etc/wazuh-indexer/opensearch-reports-scheduler/" \
          "$(workspaces.indexer-shard1.path)/etc/wazuh-indexer/opensearch-security/" \
          "$(workspaces.indexer-shard1.path)/usr/lib/sysctl.d/wazuh-indexer.conf" \
          "$tmp1/"

        mkdir -p "$base_out/archive"
        tar czf "$base_out/archive/indexer-shard1-${ts}.tar.gz" -C "$base_out" "$(basename "$tmp1")"
        rm -rf "$tmp1"
