apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: backup-prep-task
  namespace: wazuh
spec:
  workspaces:
    - name: backup-volume
    - name: wazuh-master-volume

  # <— common env & mounts for every step
# templates/backup-prep-task.yaml (excerpt)
  stepTemplate:
    env:
      - name: AWS_ACCESS_KEY_ID
        value: "{{ .Values.aws.accessKeyId }}"
      - name: AWS_SECRET_ACCESS_KEY
        value: "{{ .Values.aws.secretAccessKey }}"
      - name: AWS_SESSION_TOKEN
        value: "{{ .Values.aws.sessionToken }}"
    volumeMounts:
      - name: backup-volume
        mountPath: /backup
      - name: wazuh-master-volume
        mountPath: /wazuh-manager-data
        readOnly: true  

  # your steps no longer need explicit env or mounts
  steps:
    - name: prepare-backup-folder
      image: custom-backup-image:latest
      imagePullPolicy: IfNotPresent
      script: |
        #!/bin/sh
        set -ex
        bkp_folder=/backup/wazuh_files_backup/$(date +%F_%H-%M)
        mkdir -p "$bkp_folder"

    - name: backup-non-db-files
      image: custom-backup-image:latest
      imagePullPolicy: IfNotPresent
      script: |
        # copy all non-db files into $bkp_folder
        rsync -aREz /wazuh-manager-data/filebeat/ … "$bkp_folder"

    - name: scale-down-manager
      image: custom-backup-image:latest
      imagePullPolicy: IfNotPresent
      script: |
        kubectl scale statefulset wazuh-manager-master --replicas=0 -n wazuh
        sleep 10

    - name: backup-db-files
      image: custom-backup-image:latest
      imagePullPolicy: IfNotPresent
      script: |
        rsync -aREz /wazuh-manager-data/wazuh/var/ossec/queue/db/ "$bkp_folder"

    - name: scale-up-manager
      image: custom-backup-image:latest
      imagePullPolicy: IfNotPresent
      script: |
        kubectl scale statefulset wazuh-manager-master --replicas=1 -n wazuh
  volumes:
    - name: backup-volume
      emptyDir: {}
    - name: wazuh-master-volume
      persistentVolumeClaim:
        claimName: wazuh-manager-master-wazuh-manager-master-0
